apiVersion: v1
clusters:
- cluster:
    certificat-authority: /srv/kubernetes/ca.crt
    server: https://127.0.0.1:6443
  name: cluster-admin
contexts:
- context:
    cluster: cluster-admin
    user: admin
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: admin
  user:
    client-certificate: /srv/kubernetes/kubecfg.crt
    client-key: /srv/kubernetes/kubecfg.key
