apiVersion: v1
kind: Service
metadata:
  name: keystone
  labels:
    name: keystone
    cdxvirt/cluster-service: "true"
spec:
  type: ClusterIP
  clusterIP: KEYSTONE_CLUSTER_IP
  ports:
  - name: public
    port: 5000
    targetPort: 5000
  - name: admin
    port: 35357
    targetPort: 35357
  selector:
    name: keystone
