apiVersion: v1
kind: ReplicationController
metadata:
  name: keystone
  labels:
    name: keystone
    cdxvirt/cluster-service: "true"
spec:
  replicas: 1
  selector:
    name: keystone
  template:
    metadata:
      labels:
        name: keystone
    spec:
      containers:
      - name: keystone
        image: KEYSTONE_REGISTRY/keystone:KEYSTONE_VERSION
        imagePullPolicy: IfNotPresent
        args: ["k8sup_ldap"]
        ports:
        - containerPort: 5000
        - containerPort: 35357
        env:
        - name: LDAP_DOMAIN
          value: openldap
        - name: LDAP_PASSWORD
          value: e8fcf4a0f8384e2da2297587b0ef198e
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 30
          timeoutSeconds: 1
