apiVersion: v1
kind: Service
metadata:
  name: kubernetes-public
spec:
  ports:
  - port: 6443
  clusterIP: "None"
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kubernetes-public
subsets:
  - addresses:
      - ip: 127.0.0.1
    ports:
      - name: https
        port: 6443
